name: CI

on:
  pull_request:

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

jobs:

  pytest:
    runs-on: ubuntu-lastest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install Requirements
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -vv

