name: CI

on:
  pull_request:

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install Requirements
        run: pip install -r requirements-dev.txt

      - name: Run Pre-Commit
        run: pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install Requirements
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -vv

  build-and-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    needs: pytest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution tot Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

